[package]
name = "fledgeos"
version = "0.1.0"
authors = ["Tim McNamara <author@rustinaction.com>"]
edition = "2018"

[dependencies]
bootloader = "0.9"
x86_64 = "0.12"

[package.metadata.bootimage]
build-command = ["build"]

run-command = ["qemu-system-x86_64", "-drive", "format=raw,file={}"]

