[build]
target = "fledge.json"
#rustflags = [
# "-C", "link-self-contained=yes",
#]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

