/* Generated by Together */
#ifndef WIM__TIMERCONFIG_H
#define WIM__TIMERCONFIG_H
/******************************************************************************
*=====================    Copyright by Continental AG    ======================
*******************************************************************************
* Titel        : WIM__TimerConfig.h
*
* Description  : WIM Timer configuration
*
* Responsible  : A.Wagner, Schleissheimer GmbH
*
* Guidelines   : SMK 3.3  
*
* Template name: OOLite Codefile, Revision 1.0
*
* CASE-Tool    : Together Controlcenter, Version 6.2
*
* Revision List: (Will be filled by PVCS)
* Archive: $Log: WIM__TimerConfig_1.h  $
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 11/6/2020, KI_VS11 IC_Mid IC_Mid X005> *
*
* Code generated by: WIMgen: Version: 4.02 vom 13.01.2017, Schleissheimer GmbH 
*                on: 11/11/2020 at:9:55:41 AM
*       from WarnDB: Type:WDB Version: 1.0 vom 11/6/2020, KI_VS11 IC_Mid IC_Mid X005*              File: z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_VS11/X005_L3_LL/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 11/6/2020, KI_VS11 IC_Mid IC_Mid X005> *
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 9/3/2020, KI_VS11 IC_Mid IC_Mid X005> *
*
* Code generated by: WIMgen: Version: 4.02 vom 13.01.2017, Schleissheimer GmbH 
*                on: 9/15/2020 at:9:53:05 AM
*       from WarnDB: Type:WDB Version: 1.0 vom 9/3/2020, KI_VS11 IC_Mid IC_Mid X005*              File: z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_VS11/X005_L2_1_LL/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 9/3/2020, KI_VS11 IC_Mid IC_Mid X005> *
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 8/1/2020, KI_VS11 IC_Mid IC_Mid X005> *
*
* Code generated by: WIMgen: Version: 4.02 vom 13.01.2017, Schleissheimer GmbH 
*                on: 8/17/2020 at:11:38:29 AM
*       from WarnDB: Type:WDB Version: 1.0 vom 8/1/2020, KI_VS11 IC_Mid IC_Mid X005*              File: z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_VS11/X005_L2_LL/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 8/1/2020, KI_VS11 IC_Mid IC_Mid X005> *
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 6/22/2020, KI_VS11 IC_Mid IC_Mid X004> *
*
* Code generated by: WIMgen: Version: 4.02 vom 13.01.2017, Schleissheimer GmbH 
*                on: 6/29/2020 at:10:40:24 AM
*       from WarnDB: Type:WDB Version: 1.0 vom 6/22/2020, KI_VS11 IC_Mid IC_Mid X004*              File: z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_VS11/X004_L3_LL/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 6/22/2020, KI_VS11 IC_Mid IC_Mid X004> *
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 4/27/2020, KI_VS11 IC_Mid IC_Mid X004> *
*
* Code generated by: WIMgen: Version: 4.02 vom 13.01.2017, Schleissheimer GmbH 
*                on: 6/9/2020 at:9:09:50 AM
*       from WarnDB: Type:WDB Version: 1.0 vom 4/27/2020, KI_VS11 IC_Mid IC_Mid X004*              File: z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_VS11/X004_L2_LL/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 4/27/2020, KI_VS11 IC_Mid IC_Mid X004> *
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 15.11.2019, KI_VS11 IC_Mid IC_Mid X002 / X003> *
*
* Code generated by: WIMgen: Version: 4.02 vom 13.01.2017, Schleissheimer GmbH 
*                on: 26.11.2019 at:11:53:55
*       from WarnDB: Type:WDB Version: 1.0 vom 15.11.2019, KI_VS11 IC_Mid IC_Mid X002 / X003*              File: z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_VS11/X003_L1_LL/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 15.11.2019, KI_VS11 IC_Mid IC_Mid X002 / X003> *
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 12.08.2019, KI_VS11 IC_Mid IC_Mid X002> *
*
* Code generated by: WIMgen: Version: 4.02 vom 13.01.2017, Schleissheimer GmbH 
*                on: 04.10.2019 at:13:02:11
*       from WarnDB: Type:WDB Version: 1.0 vom 12.08.2019, KI_VS11 IC_Mid IC_Mid X002*              File: z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_VS11/X002_L1_LL/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 12.08.2019, KI_VS11 IC_Mid IC_Mid X002> *
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 29.05.2019, KI_VS11 IC_Mid IC_Mid R5> *
*
* Code generated by: WIMgen: Version: 4.02 vom 13.01.2017, Schleissheimer GmbH 
*                on: 17.06.2019 at:16:02:56
*       from WarnDB: Type:WDB Version: 1.0 vom 29.05.2019, KI_VS11 IC_Mid IC_Mid R5*              File: z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_VS11/X001_L3_LL/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 29.05.2019, KI_VS11 IC_Mid IC_Mid R5> *
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 05.04.2019, KI_VS11 IC_Mid IC_Mid R5> *
*
* Code generated by: WIMgen: Version: 4.02 vom 13.01.2017, Schleissheimer GmbH 
*                on: 30.05.2019 at:12:57:44
*       from WarnDB: Type:WDB Version: 1.0 vom 05.04.2019, KI_VS11 IC_Mid IC_Mid R5*              File: z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_VS11/X001_L2_LL/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 05.04.2019, KI_VS11 IC_Mid IC_Mid R5> *
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 22.03.2019, KI_VS30 IC_Mid IC_Mid R15> *
*
* Code generated by: WIMgen: Version: 4.02 vom 13.01.2017, Schleissheimer GmbH 
*                on: 08.04.2019 at:16:13:51
*       from WarnDB: Type:WDB Version: 1.0 vom 22.03.2019, KI_VS30 IC_Mid IC_Mid R15*              File: z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_VS30/X015_L2_LL/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 22.03.2019, KI_VS30 IC_Mid IC_Mid R15> *
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 15.02.2019, KI_VS30 IC_Mid IC_Mid R11.5> *
*
* Code generated by: WIMgen: Version: 4.02 vom 13.01.2017, Schleissheimer GmbH 
*                on: 11.03.2019 at:07:53:42
*       from WarnDB: Type:WDB Version: 1.0 vom 15.02.2019, KI_VS30 IC_Mid IC_Mid R11.5*              File: z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_VS30/X014_L3_LL/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 15.02.2019, KI_VS30 IC_Mid IC_Mid R11.5> *
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 21.08.2018, KI_VS30 IC_Mid IC_Mid R11> *
*
* Code generated by: WIMgen: Version: 4.02 vom 13.01.2017, Schleissheimer GmbH 
*                on: 22.08.2018 at:14:26:24
*       from WarnDB: Type:WDB Version: 1.0 vom 21.08.2018, KI_VS30 IC_Mid IC_Mid R11*              File: z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_VS30/X012.1_L1_LL/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 21.08.2018, KI_VS30 IC_Mid IC_Mid R11> *
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 04.07.2018, KI_VS30 IC_Mid IC_Mid R11> *
*
* Code generated by: WIMgen: Version: 4.02 vom 13.01.2017, Schleissheimer GmbH 
*                on: 16.07.2018 at:15:37:50
*       from WarnDB: Type:WDB Version: 1.0 vom 04.07.2018, KI_VS30 IC_Mid IC_Mid R11*              File: z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_VS30/X012_L3_LL/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 04.07.2018, KI_VS30 IC_Mid IC_Mid R11> *
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 09.05.2018, KI_VS30 IC_Mid IC_Mid R11> *
*
* Code generated by: WIMgen: Version: 4.02 vom 13.01.2017, Schleissheimer GmbH 
*                on: 08.06.2018 at:08:55:59
*       from WarnDB: Type:WDB Version: 1.0 vom 09.05.2018, KI_VS30 IC_Mid IC_Mid R11*              File: z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_VS30/X012_L1_LL/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 09.05.2018, KI_VS30 IC_Mid IC_Mid R11> *
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 03.11.2017, KI_VS30 IC_Mid IC_MID R8> *
*
* Code generated by: WIMgen: Version: 4.02 vom 13.01.2017, Schleissheimer GmbH 
*                on: 21.12.2017 at:10:11:39
*       from WarnDB: Type:WDB Version: 1.0 vom 03.11.2017, KI_VS30 IC_Mid IC_MID R8*              File: z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_VS30/X010_L3_LL/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 03.11.2017, KI_VS30 IC_Mid IC_MID R8> *
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 29.09.2017, KI_VS30 IC_Mid IC_MID R8> *
*
* Code generated by: WIMgen: Version: 4.02 vom 13.01.2017, Schleissheimer GmbH 
*                on: 12.10.2017 at:11:52:35
*       from WarnDB: Type:WDB Version: 1.0 vom 29.09.2017, KI_VS30 IC_Mid IC_MID R8*              File: z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_VS30/X010_L2_LL/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 29.09.2017, KI_VS30 IC_Mid IC_MID R8> *
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 03.05.2017, KI_VS30 IC_Mid IC_MID R7> *
*
* Code generated by: WIMgen: Version: 4.02 vom 13.01.2017, Schleissheimer GmbH 
*                on: 08.06.2017 at:10:03:18
*       from WarnDB: Type:WDB Version: 1.0 vom 03.05.2017, KI_VS30 IC_Mid IC_MID R7*              File: Z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_VS30/X008_L2_LL/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 03.05.2017, KI_VS30 IC_Mid IC_MID R7> *
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 23.12.2016, KI_VS30 IC_Mid IC_MID R5 / R6> *
*
* Code generated by: WIMgen: Version: 4.00 vom 08.12.2015, Schleissheimer GmbH 
*                on: 16.02.2017 at:12:47:29
*       from WarnDB: Type:WDB Version: 1.0 vom 23.12.2016, KI_VS30 IC_Mid IC_MID R5 / R6*              File: z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_VS30/X007_L2_LL/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 23.12.2016, KI_VS30 IC_Mid IC_MID R5 / R6> *
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 14.10.2016, KI_VS30 IC_Mid IC_MID R5> *
*
* Code generated by: WIMgen: Version: 4.00 vom 08.12.2015, Schleissheimer GmbH 
*                on: 14.12.2016 at:13:43:23
*       from WarnDB: Type:WDB Version: 1.0 vom 14.10.2016, KI_VS30 IC_Mid IC_MID R5*              File: z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_VS30/X006_L2_LL/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 14.10.2016, KI_VS30 IC_Mid IC_MID R5> *
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 08.08.2016, KI_VS30 IC_Entry IC_MID> *
*
* Code generated by: WIMgen: Version: 4.00 vom 08.12.2015, Schleissheimer GmbH 
*                on: 16.09.2016 at:13:46:58
*       from WarnDB: Type:WDB Version: 1.0 vom 08.08.2016, KI_VS30 IC_Entry IC_MID*              File: z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_VS30/X005_L2_LL/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 08.08.2016, KI_VS30 IC_Entry IC_MID> *
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 20.05.2016, KI_VS30 IC_Entry IC_MID> *
*
* Code generated by: WIMgen: Version: 4.00 vom 08.12.2015, Schleissheimer GmbH 
*                on: 01.07.2016 at:13:23:08
*       from WarnDB: Type:WDB Version: 1.0 vom 20.05.2016, KI_VS30 IC_Entry IC_MID*              File: R:/VDO/M_Benz/PF3/WarnDB/WarnDB_VS30/X004_L2/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 20.05.2016, KI_VS30 IC_Entry IC_MID> *
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 19.02.2016, KI_VS30 IC_Entry IC_MID> *
*
* Code generated by: WIMgen: Version: 4.00 vom 08.12.2015, Schleissheimer GmbH 
*                on: 23.03.2016 at:16:26:30
*       from WarnDB: Type:WDB Version: 1.0 vom 19.02.2016, KI_VS30 IC_Entry IC_MID*              File: R:/VDO/M_Benz/PF3/WarnDB/WarnDB_VS30/X003_L3/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 19.02.2016, KI_VS30 IC_Entry IC_MID> *
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 28.10.2015, KI_VS30 IC_Entry IC_MID> *
*
* Code generated by: WIMgen: Version: 4.00 vom 08.12.2015, Schleissheimer GmbH 
*                on: 23.02.2016 at:13:40:50
*       from WarnDB: Type:WDB Version: 1.0 vom 28.10.2015, KI_VS30 IC_Entry IC_MID*              File: R:/VDO/M_Benz/PF3/WarnDB/WarnDB_VS30/X003_L1_neue_K_Matrix/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 28.10.2015, KI_VS30 IC_Entry IC_MID> *
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 28.04.2015 23:00:00, KIG2.5 IC_High 213 High SOP E009.2 / E009.3> *
*
* Code generated by: WIMgen: Version: 4.00 vom 08.12.2015, Schleissheimer GmbH 
*                on: 09.12.2015 at:13:48:33
*       from WarnDB: Type:WDB Version: 1.0 vom 28.04.2015 23:00:00, KIG2.5 IC_High 213 High SOP E009.2 / E009.3*              File: r:/VDO/M_Benz/PF3/WarnDB/WarnDB_213_EL/Stand_E009_3_L1/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 28.04.2015 23:00:00, KIG2.5 IC_High 213 High SOP E009.2 / E009.3> *
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 09.07.2015, KIG2.5 IC_High 213 High SOP E009.2 / E009.3> *
*
* Code generated by: WIMgen: Version: 4.00 vom 08.12.2015, Schleissheimer GmbH 
*                on: 09.12.2015 at:13:53:00
*       from WarnDB: Type:WDB Version: 1.0 vom 09.07.2015, KIG2.5 IC_High 213 High SOP E009.2 / E009.3*              File: R:/VDO/M_Benz/PF3/WarnDB/WarnDB_VS30/Stand_X002.1_L0_initial (nicht offiziell)/ScreensWDBpatched.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 09.07.2015, KIG2.5 IC_High 213 High SOP E009.2 / E009.3> *
* Archive: Initial revision for VS30 (Based on 213IC-EL E009.4rel)
*
* Archive: Revision 1.10 2015/07/09 08:30:25CEST Wenske-EXT, Martin (uidj8453) 
* Archive: DC MR 48247 : WIM: BR213 E009.3 L3 Implementation
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 29.06.2015, KIG2.5 IC_High 213 High SOP E009.2 / E009.3> *
*
* Code generated by: WIMgen: Version: 3.11 vom 26.05.2015, Schleissheimer GmbH 
*                on: 30.06.2015 at:15:53:09
*       from WarnDB: Type:WDB Version: 1.0 vom 29.06.2015, KIG2.5 IC_High 213 High SOP E009.2 / E009.3*              File: r:/VDO/M_Benz/PF3/WarnDB/WarnDB_213/Stand_E009_3_L3/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 29.06.2015, KIG2.5 IC_High 213 High SOP E009.2 / E009.3> *
* Archive: Revision 1.9 2015/07/02 17:34:25CEST Wenske-EXT, Martin (uidj8453) 
* Archive: DC MR 48042 : DTR slack displaying invalid dashes instead of valid velocity - WDM 19999
* Archive: Revision 1.8 2015/06/17 18:43:38CEST Wenske-EXT, Martin (uidj8453) 
* Archive: DC MR 47461 : runtime of BasicApp_Prio2 too long
* Archive: Revision 1.7 2015/06/03 07:58:34CEST Wenske-EXT, Martin (uidj8453) 
* Archive: DC MR 47540 : AC/EL: BR213IC EL, E009.3 L1 implementation
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 29.04.2015, KIG2.5 IC_High 213 High SOP E009.2 / E009.3> *
*
* Code generated by: WIMgen: Version: 2.06 vom 28.10.2014, Schleissheimer GmbH 
*                on: 27.05.2015 at:09:35:14
*       from WarnDB: Type:WDB Version: 1.0 vom 29.04.2015, KIG2.5 IC_High 213 High SOP E009.2 / E009.3*              File: r:/VDO/M_Benz/PF3/WarnDB/WarnDB_213_EL/Stand_E009_3_L1/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 29.04.2015, KIG2.5 IC_High 213 High SOP E009.2 / E009.3> *
* Archive: Revision 1.6 2014/09/25 16:03:38CEST Wagner-EXT, Alexander (uidw3785) 
* Archive: DC MR 42664 : AC/EL: BR213EL E009 L2 implementation
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 01.08.2014, KIG2.5 IC_High 213 High SOP E009> *
*
* Code generated by: WIMgen: Version: 2.05 vom 10.07.2014, Schleissheimer GmbH 
*                on: 25.09.2014 at:10:28:28
*       from WarnDB: Type:WDB Version: 1.0 vom 01.08.2014, KIG2.5 IC_High 213 High SOP E009*              File: r:/VDO/M_Benz/PF3/WarnDB/WarnDB_213_EL/Stand_E009_L1_alte_Matrix/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 01.08.2014, KIG2.5 IC_High 213 High SOP E009> *
* Archive: Revision 1.5 2014/08/08 17:14:52CEST Wagner-EXT, Alexander (uidw3785) 
* Archive: DC MR 41957 : AC/EL: BR213EL E008 L3 Implemetation
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 21.07.2014, KIG2.5 IC_High 213 High SOP E008> *
*
* Code generated by: WIMgen: Version: 2.05 vom 10.07.2014, Schleissheimer GmbH 
*                on: 08.08.2014 at:09:05:21
*       from WarnDB: Type:WDB Version: 1.0 vom 21.07.2014, KIG2.5 IC_High 213 High SOP E008*              File: P:/WarnDB/WarnDB_213_EL/Stand_E008_L3/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 21.07.2014, KIG2.5 IC_High 213 High SOP E008> *
* Archive: Revision 1.4 2014/07/18 15:10:16CEST Wagner-EXT, Alexander (uidw3785) 
* Archive: DC MR 41419 : BR213EL/AC:E008 L2 Implementation
* Archive: Revision 1.3 2014/03/17 11:24:17CET Wagner-EXT, Alexander (uidw3785) 
* Archive: DC MR 39897 : BR213EL/AC, E007, Implementation of L2
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 07.02.2014, KIG2.5 IC_Entry 213 EL SOP E007> *
*
* Code generated by: WIMgen213 Version: 2.00 vom 18.09.2013, Schleissheimer GmbH 
*                on: 17.03.2014 at:11:12:27
*       from WarnDB: Type:WDB Version: 1.0 vom 07.02.2014, KIG2.5 IC_Entry 213 EL SOP E007*              File: Z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_213_EL/Stand_E007_L2/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 07.02.2014, KIG2.5 IC_Entry 213 EL SOP E007> *
* Archive: Revision 1.2 2013/11/22 16:05:08CET Wagner-EXT, Alexander (uidw3785) 
* Archive: DC MR 36828 : BR213EL/AC, E006, Implementation of new WarnDB
* Archive: Revision 1.1 2012/12/07 14:52:39CET Immel-EXT, Marc (uid37561) 
* Archive: Initial revision
* Archive: Member added to project /id/dag_PF3/sw/pkg/wim/adapt/BR213IC_AC_EL_SOP/project.pj
* Archive: Revision 1.3 2012/12/07 14:52:39CET Immel Marc (uid37561) (uid37561) 
* Archive: DC MR 30492: BR205/AC E011: Implementation of L2 delivery generic model part (SRSC_Style_Guide and XML files)
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 15.10.2012, KIG2 IC_Entry KIG2 EL SOP E011> *
*
* Code generated by: WIMgenPF3 Version: 1.10 vom 05.07.2012, Schleissheimer GmbH 
*                on: 05.12.2012 at:15:08:19
*       from WarnDB: Type:WDB Version: 1.0 vom 15.10.2012, KIG2 IC_Entry KIG2 EL SOP E011*              File: Z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_205/Stand_E010_pre60_L2post_121108/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 15.10.2012, KIG2 IC_Entry KIG2 EL SOP E011> *
* Archive: Revision 1.2 2012/11/21 11:49:46CET Immel Marc (uid37561) (uid37561) 
* Archive: Migration of WIM-AC from PVCS to MKS 
* Archive: - used release: DC.SW.PAC.WIM_205IC_AC_COMMON_VarW.V01.00.pre17
* Archive: Revision 1.1 2012/03/16 13:57:16CET uid37556 
* Archive: Initial revision
* Archive: Member added to project /id/dag_PF3/sw/pkg/wim/adapt/project.pj
* 
*    Rev 1.5   Nov 20 2012 18:26:42   SCHL_Marc.Immel
* DC MR 30513: BR205/AC, E010, L3 WIM
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 08.10.2012, KIG2 IC_Entry KIG2 EL SOP E010> *
*
* Code generated by: WIMgenPF3 Version: 1.10 vom 05.07.2012, Schleissheimer GmbH 
*                on: 20.11.2012 at:17:10:50
*       from WarnDB: Type:WDB Version: 1.0 vom 08.10.2012, KIG2 IC_Entry KIG2 EL SOP E010*              File: Z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_205/Stand_E010_pre60_121120_L3/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 08.10.2012, KIG2 IC_Entry KIG2 EL SOP E010> *
* 
*    Rev 1.4   Sep 07 2012 18:21:36   SCHL_Marc.Immel
* DC MR 29337: BR205 E010: Implement L2 delivery into the software frame (SRSC_Styleguide and XML files)
* DC MR 27845: ÄLP2957: Additional Hil Signals for Rearseatbeltwarning
* DC MR 27768: W205, E010/AC, WIM: Change of Partial Lowering and Mute signal Pt. II - ÄLP2994
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 17.07.2012, KIG2 IC_Entry KIG2 EL SOP E010> *
*
* Code generated by: WIMgenPF3 Version: 1.10 vom 05.07.2012, Schleissheimer GmbH 
*                on: 05.09.2012 at:11:43:40
*       from WarnDB: Type:WDB Version: 1.0 vom 17.07.2012, KIG2 IC_Entry KIG2 EL SOP E010*              File: Z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_205/Stand_E010_pre20_120905/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 17.07.2012, KIG2 IC_Entry KIG2 EL SOP E010> *
* 
*    Rev 1.3   Aug 27 2012 13:11:00   SCHL_Dirk.Gottwalles
* DC MR 29232: BR205 E009: Implementation of L3 delivery (XML files)
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 02.08.2012, KIG2 IC_Entry KIG2 EL SOP E009> *
*
* Code generated by: WIMgenPF3 Version: 1.10 vom 05.07.2012, Schleissheimer GmbH 
*                on: 27.08.2012 at:12:17:56
*       from WarnDB: Type:WDB Version: 1.0 vom 02.08.2012, KIG2 IC_Entry KIG2 EL SOP E009*              File: Z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_205/Stand_E009_pre80_120813/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 02.08.2012, KIG2 IC_Entry KIG2 EL SOP E009> *
* 
*    Rev 1.2   Jun 01 2012 09:09:02   SCHL_Dirk.Gottwalles
* DC MR 26069: W205, E009/AC, WIM: Remove CAN-Flag handling for door warning
* DC MR 25395: W205, E008/AC, WIM: Remove of CAN flag handling
* DC MR 26142: BR205 E009: Implement E009 L2 delivery into the software frame (XML files and Styleguide) (WDM38885)
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 15.05.2012, KIG2 IC_Entry SOP> *
*
* Code generated by: WIMgenPF3 Version: 1.10 vom 05.07.2012, Schleissheimer GmbH 
*                on: 27.07.2012 at:13:10:21
*       from WarnDB: Type:WDB Version: 1.0 vom 15.05.2012, KIG2 IC_Entry SOP*              File: Z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_205/Stand_E009_pre20_120521/Screens_WDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 15.05.2012, KIG2 IC_Entry SOP> *
* 
*    Rev 1.1   Mar 16 2012 14:17:26   SCHL_Dirk.Gottwalles
* DC MR 25090: W205, E008/AC, WIM: Takeover changes for WarnDB L2
*
* WimGn Segment-Start <GenerationHistory WDB Version: 1.0 vom 27.02.2011, KI_BR222 High High SOP> *
*
* Code generated by: WIMgenPF3 Version: 0.41 vom 15.01.2012, Schleissheimer GmbH 
*                on: 16.03.2012 at:13:57:15
*       from WarnDB: Type:WDB Version: 1.0 vom 27.02.2011, KI_BR222 High High SOP*              File: Z:/Projekte/VDO/M_Benz/PF3/WarnDB/WarnDB_205/Stand_E008_pre30_120302/ScreensWDB.xml
*
* WimGn Segment-End   <GenerationHistory WDB Version: 1.0 vom 27.02.2011, KI_BR222 High High SOP> *
* 
*    Rev 1.0   Nov 08 2011 14:39:04   SCHL_Dirk.Gottwalles
* Initial revision.
* 
*
*******************************************************************************/

/******************************************************************************
** Header Files (Only those that are needed in this file)
*******************************************************************************/

/* System Header Files */
#include "cdef.h"

/* Foreign headerfiles */
/* Own headerfiles */
/******************************************************************************
* Definition of exported global data used by Class
* Macros, Enumerations, Types,  Forward declarations
*******************************************************************************/
   /**
   * Description: enumeration of timers
   */
   typedef enum
   {
      WIM__nTimerReqOffDelay, /* timer for HU signal delay (can interface)         */
      WIM__nTimerDspModal,    /* timer minimal display time 500ms                  */
      WIM__nTimerDspNormal,   /* timer normal display time 5000ms                  */
      WIM__nTimerDspNormalSlack, /* timer normal display time 5000ms               */
      WIM__nTimerAcuDelModal, /* timer delay of master change 500ms (async. Acu.)  */
      WIM__nTimerAcuDelNormal,/* timer delay of master change 5000ms (async. Acu.) */
      WIM__nTimerDspDelModal, /* timer delay of master change 500ms (last Msg.)    */
      WIM__nTimerDspDelNormal,/* timer delay of master change 5000ms (last Msg.)   */
      WIM__nTimerHdlExpire,   /* validity timer for handling messages              */
      WIM__nTimerTmOutRestore,/* timer for restart RestoreWarnings if not finished */
      WIM__nTimerTmOutReset,  /* timer for restart RestoreAllWarnings if not fin   */
      WIM__nTimerHilSignal,   /* timer for HIL request signal length               */
/* WimGn Segment-Start <TOD timer enum>   */
      WIM__nTimerTurnOnDelay0,/* timer for TURN_ON_DELAY event   1                 */
      WIM__nTimerTurnOnDelay1,/* timer for TURN_ON_DELAY event   2                 */
      WIM__nTimerTurnOnDelay2,/* timer for TURN_ON_DELAY event   3                 */
      WIM__nTimerTurnOnDelay3,/* timer for TURN_ON_DELAY event   4                 */
      WIM__nTimerTurnOnDelay4,/* timer for TURN_ON_DELAY event   5                 */
      WIM__nTimerTurnOnDelay5,/* timer for TURN_ON_DELAY event   6                 */
      WIM__nTimerTurnOnDelay6,/* timer for TURN_ON_DELAY event   7                 */
      WIM__nTimerTurnOnDelay7,/* timer for TURN_ON_DELAY event   8                 */
      WIM__nTimerTurnOnDelay8,/* timer for TURN_ON_DELAY event   9                 */
      WIM__nTimerTurnOnDelay9,/* timer for TURN_ON_DELAY event  10                 */
      WIM__nTimerE2ETurnOnDelay_0x2001A8,/* timer for E2E-TURN_ON_DELAY 0x2001A8   */
      WIM__nTimerE2ETurnOnDelay_0x200487,/* timer for E2E-TURN_ON_DELAY 0x200487   */
      WIM__nTimerE2ETurnOnDelay_0x20065B,/* timer for E2E-TURN_ON_DELAY 0x20065B   */

/* WimGn Segment-End   <TOD timer enum>   */
                              /* ------- end of configuration -------------------- */
      WIM__nNoOfTimers,       /* total number of timers configured                 */
      WIM__nNoOfStaticTimers = WIM__nTimerHilSignal + 1,
                              /* number of static configured timers                */
      WIM__nFirstTimer = 0    /* first configured timer                            */
   } WIM__tenTimer;

   #define WIM__nTimerConfiguration_Manu                                            \
   /*  Timer enum                       Callback            Interval [ms]   */      \
   /*  ==================================================================== */      \
   /*  0: WIM__nTimerReqOffDelay    */  { WIM__vClearHuTxSignal   , 0            }  \
   /*  1: WIM__nTimerDspModal       */ ,{ WIM__vDspTimer          , 520          }  \
   /*  2: WIM__nTimerDspNormal      */ ,{ WIM__vDspTimer          , 5000         }  \
   /*  4: WIM__nTimerDspNormalSlack */ ,{ WIM__vDspTimer          , 5000         }  \
   /*  5: WIM__nTimerAcuDelModal    */ ,{ WIM__vDelayTimer        , 500          }  \
   /*  6: WIM__nTimerAcuDelNormal   */ ,{ WIM__vDelayTimer        , 5000         }  \
   /*  7: WIM__nTimerDspDelModal    */ ,{ WIM__vDelayTimer        , 500          }  \
   /*  8: WIM__nTimerDspDelNormal   */ ,{ WIM__vDelayTimer        , 5000         }  \
   /*  9: WIM__nTimerHdlExpired     */ ,{ WIM__vDspTimer          , 600          }  \
   /* 10: WIM__nTimerTmOutRestore   */ ,{ WIM__vResetRestoreTimer , 5000         }  \
   /* 11: WIM__nTimerTmOutReset     */ ,{ WIM__vResetRestoreTimer , 5000         }  \
   /* 12: WIM__nTimerHilSignal      */ ,{ WIM__vAcousticHilTimer  , 80           }
   
   /* WimGn Segment-Start <TOD timer config>   */
   #define WIM__nTimerConfiguration_ToD                                        \
   /*  Timer enum                       Callback            Interval [ms]   */ \
   /*  ==================================================================== */ \
   /*     WIM__nTimerTurnOnDelay0 */ ,{ NULL                 , 5000           }\
   /*     WIM__nTimerTurnOnDelay1 */ ,{ NULL                 , 5000           }\
   /*     WIM__nTimerTurnOnDelay2 */ ,{ NULL                 , 2000           }\
   /*     WIM__nTimerTurnOnDelay3 */ ,{ NULL                 , 2100           }\
   /*     WIM__nTimerTurnOnDelay4 */ ,{ NULL                 , 2000           }\
   /*     WIM__nTimerTurnOnDelay5 */ ,{ NULL                 , 1000           }\
   /*     WIM__nTimerTurnOnDelay6 */ ,{ NULL                 , 20000          }\
   /*     WIM__nTimerTurnOnDelay7 */ ,{ NULL                 , 1000           }\
   /*     WIM__nTimerTurnOnDelay8 */ ,{ NULL                 , 12000          }\
   /*     WIM__nTimerTurnOnDelay9 */ ,{ NULL                 , 2000           }\
   /* WIM__nTimerE2ETurnOnDelay_0x2001A8 */ ,{ NULL          , 600            }\
   /* WIM__nTimerE2ETurnOnDelay_0x200487 */ ,{ NULL          , 300            }\
   /* WIM__nTimerE2ETurnOnDelay_0x20065B */ ,{ NULL          , 1000           }

   /*
   * Description: number of generated timers
   */
   #define WIM__nNumGenTimers 13


/* WimGn Segment-End   <TOD timer config>   */

#define WIM__nTimerConfiguration   WIM__nTimerConfiguration_Manu  \
                                   WIM__nTimerConfiguration_ToD

#endif /* WIM__TIMERCONFIG_H */
