//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by InetDownload.rc
//
#define IDD_INETDOWNLOAD_DIALOG         102
#define IDS_HTTPDOWNLOAD_FILESTATUS     102
#define IDS_HTTPDOWNLOAD_CONNECTED      103
#define IDS_HTTPDOWNLOAD_RESOLVING_NAME 104
#define IDS_HTTPDOWNLOAD_RESOLVED_NAME  105
#define IDS_HTTPDOWNLOAD_CONNECTING     106
#define IDS_HTTPDOWNLOAD_REDIRECTING    107
#define IDS_HTTPDOWNLOAD_GETTING_FILE_INFORMATION 108
#define IDS_HTTPDOWNLOAD_FAIL_PARSE_ERROR 109
#define IDS_HTTPDOWNLOAD_GENERIC_ERROR  110
#define IDS_HTTPDOWNLOAD_FAIL_CONNECT_SERVER 111
#define IDS_HTTPDOWNLOAD_INVALID_SERVER_RESPONSE 112
#define IDS_HTTPDOWNLOAD_INVALID_HTTP_RESPONSE 113
#define IDS_HTTPDOWNLOAD_ERROR_READFILE 114
#define IDS_HTTPDOWNLOAD_PERCENTAGE     115
#define IDS_HTTPDOWNLOAD_RETRIEVING_FILE 116
#define IDS_HTTPDOWNLOAD_OF             117
#define IDS_HTTPDOWNLOAD_SECONDS        118
#define IDS_HTTPDOWNLOAD_MINUTES        119
#define IDS_HTTPDOWNLOAD_MINUTES_AND_SECONDS 120
#define IDS_HTTPDOWNLOAD_BYTES          121
#define IDR_MAINFRAME                   122
#define IDS_HTTPDOWNLOAD_KILOBYTES      123
#define IDD_HTTPDOWNLOAD                124
#define IDS_HTTPDOWNLOAD_MEGABYTES      125
#define IDR_HTTPDOWNLOAD_ANIMATION      126
#define IDS_HTTPDOWNLOAD_TIMELEFT       127
#define IDS_HTTPDOWNLOAD_BYTESPERSECOND 128
#define IDS_HTTPDOWNLOAD_KILOBYTESPERSECOND 129
#define IDS_HTTPDOWNLOAD_OK_TO_OVERWRITE 130
#define IDS_HTTPDOWNLOAD_FAIL_FILE_OPEN 131
#define IDS_HTTPDOWNLOAD_ABORTING_TRANSFER 132
#define IDS_HTTPDOWNLOAD_FAIL_FILE_SEEK 133
#define IDC_ANIMATE1                    1000
#define IDC_STATUS                      1001
#define IDC_FILESTATUS                  1002
#define IDC_PROGRESS1                   1003
#define IDC_TIMELEFT                    1004
#define IDC_TRANSFER_RATE               1005
#define IDC_DOWNLOAD                    1005
#define IDC_URL                         1006
#define IDC_FILE                        1007
#define IDC_HTTP_USER                   1008
#define IDC_HTTP_PASSWORD               1009
#define IDC_OFFSET                      1010
#define IDC_PROXY_USER                  1011
#define IDC_PROXY_PASSWORD              1012
#define IDC_CONNECTION                  1013
#define IDC_PROMPT_FILE_OVERWRITE       1014
#define IDC_PROMPT_FOR_PROXY_DETAILS    1015
#define IDC_PROMPT_FOR_HTTP_DETAILS     1016
#define IDC_PROXYSERVER                 1017
#define IDC_LIMIT                       1018
#define IDC_NO_URL_REDIRECT             1019
#define IDC_HTTP_PREAUTHENTICATION      1020
#define IDC_PROXY_PREAUTHENTICATION     1021
#define IDC_REFERRER                    1022
#define IDC_ACCEPT_TYPES                1023
#define IDC_IGNORE_REDIRECT_TO_HTTP_ERRORS 1024
#define IDC_IGNORE_REDIRECT_TO_HTTPS_ERRORS 1025
#define IDC_PROMPT_CERTIFICATE          1026
#define IDC_IGNORE_REVOCATION_PROBLEMS  1027
#define IDC_IGNORE_UNKNOWN_CA           1028
#define IDC_IGNORE_WRONG_USAGE          1029
#define IDC_IGNORE_CERT_CN_INVALID      1030
#define IDC_IGNORE_CERT_DATE_INVALID    1031

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1023
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
