; Listing generated by Microsoft (R) Optimizing Compiler Version 19.15.26730.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG88998 DB	'Hello x64 World!', 00H
CONST	ENDS
PUBLIC	main
EXTRN	__imp_GetStdHandle:PROC
EXTRN	__imp_WriteFile:PROC
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+66
	DD	imagerel $unwind$main
pdata	ENDS
xdata	SEGMENT
$unwind$main DD	010401H
	DD	08204H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
written$ = 48
main	PROC
; File v:\masm64\hw.cpp
; Line 3
$LN3:
	sub	rsp, 72					; 00000048H
; Line 4
	mov	DWORD PTR written$[rsp], 0
; Line 6
	mov	ecx, -11				; fffffff5H
	call	QWORD PTR __imp_GetStdHandle
	mov	QWORD PTR [rsp+32], 0
	lea	r9, QWORD PTR written$[rsp]
	mov	r8d, 16
	lea	rdx, OFFSET FLAT:$SG88998
	mov	rcx, rax
	call	QWORD PTR __imp_WriteFile
; Line 7
	xor	eax, eax
	add	rsp, 72					; 00000048H
	ret	0
main	ENDP
_TEXT	ENDS
END
