/* Generated by Together */
#ifndef WIM__COMPLEXDRAW_H
#define WIM__COMPLEXDRAW_H
/******************************************************************************
*=====================    Copyright by Continental AG    ======================
*******************************************************************************
* Titel        : WIM__ComplexDraw.h
*
* Description  : configuration header of data-class (internal):
*                Contains message configuration data:
*                - message attributes for view/state handling
*                - request control containers
*                - priority definitions/levels
*
* Environment  : OSEK, JCP (NEC V850)
*
* Responsible  : L.Gruenewald, Schleissheimer GmbH
*
* Guidelines   : SMK 3.3  
*
* Template name: OOLite Codefile, Revision 1.0
*
* CASE-Tool    : Together Controlcenter, Version 6.2
*
* Revision List: (Will be filled by PVCS)
* Archive: $Log: WIM__ComplexDraw.h  $
* Archive: Revision 1.1 2012/05/18 15:47:50CEST Immel-EXT, Marc (uid37561) 
* Archive: Initial revision
* Archive: Member added to project /id/dag_PF3/sw/pkg/wim/adapt/project.pj
* Archive: Revision 1.1 2012/05/18 15:47:51CEST uid37556 
* Archive: Initial revision
* Archive: Member added to project /id/dag_PF3/sw/pkg/wim/adapt/project.pj
* Archive: Revision 1.1 2012/04/27 14:35:01CEST Gottwalles Dirk (uid37556) (uid37556) 
* Archive: Initial revision
* Archive: Member added to project /id/dag_PF3/sw/pkg/wim/core/project.pj
*
****************************************************************************/

/******************************************************************************
** Header Files (Only those that are needed in this file)
*******************************************************************************/

/* System Header Files */
#include "cdef.h"

/* Foreign headerfiles */

/* Own headerfiles */


/**
* The function initializes the acoustic class
*   @return  void
*   @param   enMsg: Message that is requested next
*   @author  D.Gottwalles, Schleissheimer GmbH 
*/
void WIM__vHandleComplexDraw(WIM_tenMsg enMsg);

/**
* The function initializes the acoustic class
*   @return  void
*   @param   enMsg: Message that is requested next
*   @author  D.Gottwalles, Schleissheimer GmbH 
*/
void WIM__vHandleComplexSlackDraw(WIM_tenMsg enMsg);



/**
* Timer callback function.
* Called if one of the complex draw timers have elapsed.
*   @return  void
*   @param   enTimer: Timer identifier
*           xCorrTag: Correlation tag (message Id)
*   @author  D.Gottwalles, Schleissheimer GmbH
*/
void WIM__vCplxDrawIconTimer(WIM__tenTimer enTimer, WIM__txCorrTag xCorrTag);

#endif /* WIM__COMPLEXDRAW_H */
