/* Generated by Together */
#ifndef WIM__COMPLEXCONDITION_H
#define WIM__COMPLEXCONDITION_H
/******************************************************************************
*=====================    Copyright by Continental AG    ======================
*******************************************************************************
* Titel        : WIM__ComplexCondition.h
*
* Description  : configuration header of data-class (internal):
*                Contains message configuration data:
*                - message attributes for view/state handling
*                - request control containers
*                - priority definitions/levels
*
* Environment  : OSEK, JCP (NEC V850)
*
* Responsible  : M.Immel, Schleissheimer GmbH
*
* Guidelines   : SMK 3.3  
*
* Template name: OOLite Codefile, Revision 1.0
*
* CASE-Tool    : Together Controlcenter, Version 6.2
*
* Revision List: (Will be filled by PVCS)
* Archive: $Log: WIM__ComplexCondition.h  $
* Archive: Revision 1.3 2014/07/18 16:10:04CEST Wagner-EXT, Alexander (uidw3785) 
* Archive: DC MR 40950 : BR213-EL/E008, WIM: Reaction of hybrid warning 0x200542 on wrong CAN signal - WDM 101213
* Archive: Revision 1.2 2014/03/21 12:59:06CET Wagner-EXT, Alexander (uidw3785) 
* Archive: DC MR 39839 : BR205 E013: ALP3289 new warning 0x200542(Hybrid) 
* Archive: DC MR 40021 : WIM: Sound of FCW warning is not retriggered after reset
* Archive: DC MR 39892 : BR213EL, E007, Implementation of L2
* Archive: Revision 1.1 2012/12/21 13:23:08CET Immel-EXT, Marc (uid37561) 
* Archive: Initial revision
* Archive: Member added to project /id/dag_PF3/sw/pkg/wim/adapt/project.pj
* Archive: Revision 1.1 2012/12/21 13:23:09CET Immel Marc (uid37561) (uid37561) 
* Archive: Initial revision
* Archive: Member added to project /id/dag_PF3/sw/pkg/wim/adapt/project.pj
****************************************************************************/

/******************************************************************************
** Header Files (Only those that are needed in this file)
*******************************************************************************/

/* System Header Files */
#include "cdef.h"

/* Foreign headerfiles */

/* Own headerfiles */


/**
* Check conditions for convertible top movement 0x200527
*   @return  void
*   @param   void
*   @author  M.Immel, Schleissheimer GmbH 
*/
void WIM__vCheckConvertibleTop(void);

/*
*  Check conditions for hybrid warning 0x200542 
*  @return  none
*  @param   void
*  @author  A.Wagner, Schleissheimer GmbH
*/
void WIM__vCheckOperationModeHybrid(void);

/*
*  ReCheck hybrid warning 0x200542 
*  @return  none
*  @param   void
*  @author  A.Wagner, Schleissheimer GmbH
*/
void WIM__vReCheckOperationModeHybrid(void);

#endif /* WIM__COMPLEXCONDITION_H */
