/* Generated by Together */
#ifndef WIM__ICOM_AC_H
#define WIM__ICOM_AC_H
/******************************************************************************
*======================= Copyright by Continental Automotive AG ===============
*******************************************************************************
* Titel        : WIM__ICom_AC.h
*
* Description  : Package private interface of icom-class:
*                ICom services AC
*                Private class that manages DPOOL access
*                package WIM
*
* Environment  : OSEK, JCP (NEC )
*
* Responsible  : A.Wagner, Schleissheimer GmbH
*
* Guidelines   : SMK 3.3  
*
* Template name: OOLite Codefile, Revision 1.0
*
* CASE-Tool    : Together Controlcenter, Version 6.2
*
* Revision List: (Will be filled by PVCS)
* Archive: $Log: WIM__ICom_AC.h  $
* Archive: Initial revision for VS11 (Based on 213IC-EL E009.4rel)
*
* Archive: Revision 1.5 2015/06/17 18:42:54CEST Wenske-EXT, Martin (uidj8453) 
* Archive: DC MR 47461 : runtime of BasicApp_Prio2 too long
* Archive: Revision 1.4 2014/04/08 17:13:11CEST Wagner-EXT, Alexander (uidw3785) 
* Archive: DC MR 40060 : 213/AC, WIM: Sending of SLACK HIL ID on CAN
* Archive: Revision 1.3 2014/03/28 15:24:04CET Wagner-EXT, Alexander (uidw3785) 
* Archive: DC MR 39277 : WIM: Sending of WIM HIL ID on CAN
* Archive: Revision 1.2 2013/09/17 13:10:17CEST Immel-EXT, Marc (uid37561) 
* Archive: DC MR 34947: prevent PF3 compiler warnings
* Archive: DC MR 34940: BR213, WIM: Acoustic of door warning shall not be retriggered by another door
* Archive: DC MR 34883: WIM: Persistent storage of warn states for wake-IC warnings
* Archive: Revision 1.1 2012/11/21 11:49:05CET Immel-EXT, Marc (uid37561) 
* Archive: Initial revision
* Archive: Member added to project /id/dag_PF3/sw/pkg/wim/adapt/BR213IC_AC_EL_SOP/project.pj
* Archive: Revision 1.2 2012/11/21 11:49:05CET Immel Marc (uid37561) (uid37561) 
* Archive: Migration of WIM-AC from PVCS to MKS 
* Archive: - used release: DC.SW.PAC.WIM_205IC_AC_COMMON_VarW.V01.00.pre17
* Archive: Revision 1.1 2011/11/08 13:03:18CET uid37556 
* Archive: Initial revision
* Archive: Member added to project /id/dag_PF3/sw/pkg/wim/adapt/project.pj
* 
*    Rev 1.1   May 18 2012 16:55:54   SCHL_Dirk.Gottwalles
* DC MR 25587: WDM21151/34246/35637: SBW/WIM Acoustic corrections
* DC MR 25914: W205, E009/AC, HIL: Mapping of WIM sound types
* 
* 
*    Rev 1.0   Nov 08 2011 14:39:04   SCHL_Dirk.Gottwalles
* Initial revision.
* 
*
****************************************************************************/

/***************************************************************************
** Header Files (Only those that are needed in this file)
****************************************************************************/

/* System Header Files */
#include "cdef.h"

/* Foreign headerfiles */

/* Own headerfiles */
#include "WIM__Types.h"               /* package internal type definitions                 */

/******************************************************************************
* Definition of exported global data used by Class
* Macros, Enumerations, Types,  Forward declarations
*******************************************************************************/


/******************************************************************************
* CLASS DEFINITION
*******************************************************************************/
#ifdef TOGETHER /* open C++ class */

/**
* ICom services class
*/
class WIM__IComAC {
public: 
#endif

/******************************************************************************
*   Class Attributes
*******************************************************************************/

/* System Wide Scope */
#ifdef TOGETHER
public:
#endif

#ifdef QAC_Analysis
#pragma PRQA_MESSAGES_OFF 2300
#endif /* QAC_Analysis */

/* Package Global Scope */

   /**
   * Storage for the last HIL-ID-displayed, posted from GC by ICom.
   * @range  uint32
   * @values possible HIL-IDs and WIM__nInvalidHilId
   */
   extern uint32 WIM__u32CurrentDspMsg;
   
   /**
   * WakeIC state of messages 
   * @range  bool
   * @values state true/false
   */
   extern bool WIM__aboWakeICStates[];

#ifdef QAC_Analysis
#pragma PRQA_MESSAGES_ON 2300
#endif /* QAC_Analysis */

/* File Local Scope */
#ifdef TOGETHER
private:
#endif

/******************************************************************************
*   Class Operations
*******************************************************************************/

/* Package Global Scope */
#ifdef TOGETHER
public:
#endif

/**
* Initialise ICom internal components.
*   @return  void
*   @param   void
*   @author  L.Gruenewald, Schleissheimer GmbH 
*/
void WIM__vIComInit_AC(void);

/**
* Displacement on AC for Central event function on GC.
* Sending all received Events with the pending Msg by using the ICom mechanism
* into the GC to process this Data.
* Additionally the Registered Flag (redundant copy on Ac) is set after an 
* Successfully sending.
*   @return  ---
*   @param   enMsg: Message identifier, enEvt: Event identifier
*   @author  L.Gruenewald, Schleissheimer GmbH 
*/
void WIM__vOnEvent_AC(WIM_tenMsg enMsg, WIM__tenEventIntern enEvt);

/**
* Send feedback for Gc that Ac had finished Restore all Warnings
* and further comming OnEvent - QueueEvents has to be used.
*   @return  void
*   @param   void
*   @author  L.Gruenewald, Schleissheimer GmbH 
*/
void WIM__vFinishedRestoreWarningsActivateICom(void);

/**
* Send feedback for Gc that Ac had finished re-check all Warnings
* and the Scheduler has to be restarted, retriggered.
*   @return  void
*   @param   void
*   @author  L.Gruenewald, Schleissheimer GmbH 
*/
void WIM__vFinishedRestoreWarnings_AC(void);

/**
* Send feedback for Gc that Ac had finished Reset all Warnings
* and further comming OnEvent-QueueEvents has to be used.
*   @return  void
*   @param   void
*   @author  L.Gruenewald, Schleissheimer GmbH 
*/
void WIM__vFinishedResetWarningsActivateICom(void);

/**
* PowerOn initialisation of State Handler. Only the redundant copy of StateHandler Flags
* are initiated this time!!!
*   @return  void
*   @param   none
*   @author  L.Gruenewald, Schleissheimer GmbH 
*/
void WIM__vStateHandlerInit_AC(void);    

/**
* PowerOn initialisation of WakeIC states. 
*   @return  void
*   @param   none
*   @author  A.Wagner, Schleissheimer GmbH 
*/
void WIM__vWakeIcStateInit(void);

/**
* Save wake-ic state bits to DPOOL data (persistent memory)
*   @return  void
*   @param   none
*   @author  A.Wagner, Schleissheimer GmbH 
*/
void WIM__vWakeIcStateDeInit(void);

/**
* Helper function to get the WakeIC state bit out of a uint32 variable
*   @return  void
*   @param   none
*   @author  A.Wagner, Schleissheimer GmbH 
*/
bool WIM__boGetWakeIcStateBit(uint32 u32SaveWakeIcState, uint32 u32CountValue);

/**
* This function is called by Interface function on reception of an Event
* which is processed by WIM__ICom
*   @return  void
*   @param   EVHD_tenReceiveEvent enEvent, contains the received Event.
*   @author  L.Gruenewald, Schleissheimer GmbH 
*/
void WIM__vDoDpoolEventsByICom_AC(EVHD_tenReceiveEvent enEvent);

/**
* Check DPOOL data if it is a WIM Hil Id.
*   @return  void
*   @param   void
*   @author  A.Wagner, Schleissheimer GmbH 
*/
void WIM__vCheckDPOOLWimHilId(void);

/**
* Check DPOOL data if it is a Slack Hil Id.
*   @return  void
*   @param   void
*   @author  A.Wagner, Schleissheimer GmbH 
*/
void WIM__vCheckDPOOLSlackHilId(void);

/**
* Inform applications to re-check message conditions after message reset
*   @return  void
*   @param   void
*   @author  T.Godemann, Schleissheimer GmbH 
*/
void WIM__vCheckComplexWarnings_AC(void); 


/* File Local Scope */
#ifdef TOGETHER
private:
#endif

#ifdef TOGETHER /* close the C++ class */
};
#endif
/********************
**  CLASS END
*********************/
#endif /* WIM__ICOM_AC_H */
